### PR TITLE
fix/AB#69129_Filters-not-working-with-date

### PR DESCRIPTION
**Pull request by LenaelleL**
# Description

This branch is a way to re-add modifications done in this PR : https://github.com/ReliefApplications/ems-frontend/pull/1741 and later deleted for scope reasons. These modifications allow the user to filter by date without taking timezones into account.

There was a second issue mentioned in the ticket (quick filters not working with dates in specific conditions) but I was not able to reproduce this bug even though a video showing the bug was linked to the ticket

## Useful links

- Link to ticket : https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/69129

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Tested on local with own database, with UAT database and directly on UAT environment
- [x] Tested with different resources including the exact one used in the WHO video

## Screenshots

The time zone issue is fixed (here shown on local environment with UAT database) : 
ticket69129_notimeZoneIssue

The bug when filtering with 2 fields cannot be reproduced even on UAT (the timezone bug here is still showing because we are on UAT environment) : 

ticket69129_cannotReproduce

# Checklist:

( * == Mandatory ) 

- [x] * I have set myself as assignee of the pull request
- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [x] * I have commented my code, particularly in hard-to-understand areas
- [x] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AntoineRelief** [comment]
@LenaelleRelief 
please never create a branch from main
that's perhaps just a PR issue there, but we need to double check that always

**Comment by LenaelleL** [comment]
> @LenaelleRelief please never create a branch from main that's perhaps just a PR issue there, but we need to double check that always

Yeah sorry, I forgot to select the correct branch on the PR ! Won't happen again

**Review by MwanPygmay — APPROVED** [review]
- tested, could see the bug on uat, did not manage to reproduce in local.
- Could check that indeed filter query was sent with a time zone offset, and that this change effectively changes the filter input.
- Changed naming to avoid confusion

**Comment by Matthis-M-ReliefApps** [comment]
Replaced by #2203 Hence closing

**Pull request closed without merging**
