### PR TITLE
Fix/ab#70863 abc breadcrumb going outside of bounds

### PR DESCRIPTION
**Pull request by unai-reliefapp**
# Description

feat: add minimal display when breadcrumb width is off limit using hover effect
feat: add method to check on window resize if breadcrumb text should be displayed or minimal display should be used
fix: property names in html to make it more legible

## Ticket

[Link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/70863)

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Improvement (refactor or addition to existing functionality)

# How Has This Been Tested?

Please refer to videos below

## Screenshots

https://github.com/ReliefApplications/oort-frontend/assets/123092672/e032f99b-3cc3-417a-9b40-b3bd775949d4

https://github.com/ReliefApplications/oort-frontend/assets/123092672/1d1f4322-5b0c-4bb6-8765-de643f3a4a0b

# Checklist:

( * == Mandatory ) 

- [X] * The pull request is linked to an existing milestone
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
The solution proposed works BUT it's jiggly, slightly misaligned (the / in the video are not aligned) and the text is spread across 2 lines when it shouldn't.

https://github.com/ReliefApplications/oort-frontend/assets/60609610/9bd8c65c-3d3d-4720-96c9-def8d21fa25a

**Comment by unai-reliefapp** [comment]
Fix word break issue plus switch to new 2.0.x branch as base in the last commit

https://github.com/ReliefApplications/oort-frontend/assets/123092672/9afcf56b-217b-4ca8-80da-5f77f628acdc

**Review by ghost — APPROVED** [review]
Works as intended.

I pushed a small UI fix to allow the user to not only hover the breadcrumb with the ... but also a few pixels left and right (see video), to make it easier for them, for accessibility reasons.
(I hope I didnt break anything 😬)

Changes were:
  - Added padding instead of margin
  - Changed mouseover and mouseout to mouseenter and mouseleave for less flickering
  - Moved the event listeners to the parent li element for larger hoverable area


https://github.com/ReliefApplications/oort-frontend/assets/60609610/f8528bf4-ceab-4ce6-a880-cb2656481e9d

**Review by AntoineRelief — APPROVED** [review]

**Comment by AntoineRelief** [comment]
@JulienKerlero @unai-reliefapp 
good work ✅
and well done for the PR, exactly what I asked for 🤩

**Pull request merged**
