### PR TITLE
Bugfix/ab#77743 abc page is taking too much resource when showing a grid with many columns records

### PR DESCRIPTION
**Pull request by unai-reliefapp**
# Description

feat: add grid-data-formatter file containing all the needed methods to format and assign each grid row data to be available in the html grid template
feat: replace all the dynamic checks in grid template by the static properties built in the grid-data-formatter file
feat: apply this data format on every data or fields change cycle hook

## Useful links

- [Link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/77743)

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Improvement (refactor or addition to existing functionality)

# How Has This Been Tested?

Please refer to video below

## Screenshots

Grid handling 100 items
https://github.com/ReliefApplications/ems-frontend/assets/123092672/081bda3f-df17-4fa2-beb8-12cb4e240a1c

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings

### CODE REVIEW

**Comment by AntoineRelief** [comment]
@unai-reliefapp 
far better like that!

a few things I noticed:
- url sometimes cause an issue. I tried with the same sample of data than in UAT, and that broke the UI, telling that dataitem.url was not defined
- performance is still not so good. Perhaps you can have a look at this one:
https://www.telerik.com/kendo-angular-ui/components/grid/browser-performance/

**Review by AntoineRelief — CHANGES_REQUESTED** [review]
some changes to be done, regarding missing properties in the dataItem & performance

**Comment by unai-reliefapp** [comment]
> @unai-reliefapp far better like that!
> 
> a few things I noticed:
> 
> * url sometimes cause an issue. I tried with the same sample of data than in UAT, and that broke the UI, telling that dataitem.url was not defined
> * performance is still not so good. Perhaps you can have a look at this one:
>   https://www.telerik.com/kendo-angular-ui/components/grid/browser-performance/

About the performance, i left the function of tooltip display for ellipsed content because the condition to trigger that takes in account a lot of dynamic changes(as columns can be resized, added/removed, window can also be resized) that we have to listen to constantly, and I didnt see any collapse in the UI.

I'll also add/ take a look to the telerik docs you send to complement the ticket 👍 
KR, Unai

**Comment by unai-reliefapp** [comment]
> some changes to be done, regarding missing properties in the dataItem & performance

Hi @AntoineRelief about the virtualization that the docs present, for the column virtualization we'll have to first merge the automatic column width set PR, as column virtualization requires a fixed with for all the columns(plus also on add/remove columns and recalculating the columns width values, I dont know how this would behave.
image
Also looks like it's not possible to have sticky and virtualization for columns at the same time;
image

Also according to doces cannot have virtual scroll and pagination at the same time, setting virtual scroll to true makes the pagination bar dissappear

KR, Unai

**Comment by unai-reliefapp** [comment]
> > @unai-reliefapp far better like that!
> > a few things I noticed:
> > 
> > * url sometimes cause an issue. I tried with the same sample of data than in UAT, and that broke the UI, telling that dataitem.url was not defined
> > * performance is still not so good. Perhaps you can have a look at this one:
> >   https://www.telerik.com/kendo-angular-ui/components/grid/browser-performance/
> 
> About the performance, i left the function of tooltip display for ellipsed content because the condition to trigger that takes in account a lot of dynamic changes(as columns can be resized, added/removed, window can also be resized) that we have to listen to constantly, and I didnt see any collapse in the UI. But i'll see how can i improve this one also
> 
> I'll also add/ take a look to the telerik docs you send to complement the ticket 👍 KR, Unai

**Comment by unai-reliefapp** [comment]
@AntoineRelief , fixed the isEllipsisActive avoiding the use of DOM check using the newly discovered `@Attribute` 😄 
There are no functions that constantly check the dom for cells in the grid now, anyway I can check if the virtualization is doable somehow, let's see if just with this performance issues are not that critical.

KR, Unai

**Comment by AntoineRelief** [comment]
@unai-reliefapp 
I think you pushed back the commits I wanted to remove about eslint

If you can see how to remove them

I'll test performance in the meantime

**Pull request merged**
