### PR TITLE
Export

### PR DESCRIPTION
**Pull request by SianaDicheva**
# Description
 
Dashboards can be exported to PDF, PNG, or JPEG Format and will be exported as the default size.

- Widgets shown on the dashboard at the current time will be exported (if a user deletes a widget this widget won't be present in the export)
- When Exporting a dashboard with a map in either, PDF or PNG the base map and web maps are replaced with a grey/ Black and white map with the layers persisted.
- Included ability to add Header and Footer (header contains current date, name of the dashboard and link to page on the bottom).
- The Widget toolbar, etc. shouldn’t be in view.
 
 
## Useful links
- https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/52683
 
## Type of change
 
- [X] New feature (non-breaking change which adds functionality)
 
# How Has This Been Tested?
 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
 
- [ ] Test A
- [ ] Test B
 
## Screenshots
 
Please include screenshots of this change. If this issue is only back-end related, and does not involve any visual change of the platform, you can skip this part.
 
# Checklist:
 
( * == Mandatory )
 
- [ ] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [ ] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [ ] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by matheus-relief** [comment]
Hey @SianaDicheva and @HasnatL-Adapptlimited, so I checked the PR and I have two main concerns: 

* In the ticket description, it says "When widgets include pagination, the Admin should be able to choose whether all pages of the widget data will be exported or only the currently visible page", which wasn't implemented as far as I can tell
* It also says about orientation, which as far as I can tell, was not implemented either, there are just a few translation keys added, but not used anywhere

Other than that, found a few other issues, that would be easier to resolve
## Code standards
* Missing some JSDocs, linting with `npm run lint` highlights all of those
* Underutilization of our UI library (for example, there are the `ui-checkbox` and `ui-select-menu` components, that could be used in the [dashboard-export-action.component.html](https://github.com/ReliefApplications/ems-frontend/pull/2350/files#diff-c6d1257240f36c6ccdf56417e37b43fe9eadf89be2a50949da703e3197b68108)
* On that same file, I can see that there's at least one hardcoded string, that should be added to the language files

## Other minor concerns
* `mapReadyForExportSubscription` seems to do nothing on the dashboard component
*  could be wrong  as it's been a long time since I've worked on anything map related, but I don't think the solution with the mapStatusService would always work if there is more than one map in the dashboard because if just one of them is ready to be exported, the export would go through with it at once. The exported pdf bellow I purposefully added a bit of delay on the `this.mapStatusService.isExporting$`  subscription in one of the maps and in fact the basemap is not showing, although like I said, not sure this would ever happen with real life usage
* When exporting a dashboard with a dashboard filter configured, it looks a bit off IMO, specially the edit icon

Example: [Dashboard (6).pdf](https://github.com/ReliefApplications/ems-frontend/files/14140988/Dashboard.6.pdf)

cc @AntoineRelief

**Comment by HasnatL-Adapptlimited** [comment]
Hey @matheus-relief,

Thank you for the detailed review 
I have taken note and started making changes:


## Changes made so far:
- Cleaned up the linting errors (came up with 4 warnings not sure if this is the same on your side),
- Cleaned up the hard coded string
- Working on ui-select-menu and ui-checkbox, it keeps closing the dialog box when a user tries to interact with it (do you have any suggestions for this? or where I should look in the uiFormFieldDirective or select-menu classes) or am I able to just reuse the styles.

## Quick note on the **orientation**:
- Since the paper size is auto, kendo ui doesn't allow for orientation to be changed, but looking into ways this can be done, as having other paper sizes gave so many options compared to auto

## **Map Ready for export subscription:**
The use for this subscription is to sends to the dashboard when the map has fully transitioned to the b+w map before exporting.

- some changes will be made so that the map status service has a count of all the maps in the dashboard and doesn't let the dashboard get exported until all these

Also will find a more appropriate place to put the **isExporting** subscription so there is less of a delay.

Also working on the pagination.

**Comment by HasnatL-Adapptlimited** [comment]
Implemented a counter to track how many maps are on a dashboard before exporting, there will be more of a delay the more maps there are but trying to find solutions to decrease this delay.

- Pagination (still in progress)
- UI components (still in progress)

**Comment by matheus-relief** [comment]
Hey @HasnatL-Adapptlimited I wasn't really sure how to explain the usage of our components, so instead I forked it and pushed a few changes here https://github.com/adappt/oort-frontend/pull/2

The problem you were having I'm almost certain is related to the ui-dialog. You can check that and if the usage is still not clear I'd be happy to schedule a call so I can try to better explain it.


https://github.com/ReliefApplications/ems-frontend/assets/102038450/7e920370-19be-4601-a3a4-9bba90a971ba

**Comment by HasnatL-Adapptlimited** [comment]
Hey @matheus-relief , cc: @AntoineRelief

UI Dialog problems were resolved using your PR, thank you for fixing (will be using the ui-dialog from now on whenever adding a dialog box) and as discussed in last weeks weekly call, pagination will not be added to this PR.

**Comment by AntoineRelief** [comment]
@HasnatL-Adapptlimited 

I noticed some issues:
- widgets using images can't export these images when they come from external url, like:
https://whoemssafepsta02.blob.core.windows.net/hazards/societal.svg
- I tried exporting the map, and in most cases, it failed to export, resulting either in a map with grey background, or with a grey stripe in the middle. In addition, it seems some layers styling isn't available in the export. For example, color dots layers won't look the same between the map itself, and the export

**Comment by HasnatL-Adapptlimited** [comment]
> @HasnatL-Adapptlimited
> 
> I noticed some issues:
> 
> * widgets using images can't export these images when they come from external url, like:
>   https://whoemssafepsta02.blob.core.windows.net/hazards/societal.svg
> * I tried exporting the map, and in most cases, it failed to export, resulting either in a map with grey background, or with a grey stripe in the middle. In addition, it seems some layers styling isn't available in the export. For example, color dots layers won't look the same between the map itself, and the export

Hey @AntoineRelief, cc: @matheus-relief 

Thank you for the update and response.
With regards to grey map, this was the proposed and accepted solution by Jered and stakeholders so this behaviour is expected.

I have tested exporting images insert via url and will look into fixing this and do you have any examples of layers that aren't working with the export?

**Comment by AntoineRelief** [comment]
@HasnatL-Adapptlimited 

An example of the difference between exported map & map as it appears on the web page

you can see the color of the point is set to black, even if it should be blue

Events
Capture d’écran 2024-02-28 à 20 20 50

Another example:
in the webpage:
Capture d’écran 2024-02-28 à 20 24 19

in the export:
Capture d’écran 2024-02-28 à 20 24 43


While doing this test, I noticed that the style from the dashboard filter is also being removed ( dropdowns don't look well )

+ some pages were fully blank
I think the pdf doesn't allow dashboard using 'fit' mode ( that you can select opening dashboard settings ):
Capture d’écran 2024-02-28 à 20 25 00

**Pull request closed without merging**
