### PR TITLE
AB#80331 ABC - Add edition warning to tab widgets

### PR DESCRIPTION
**Pull request by Maximo-reliefapps**
# Description

Tab widgets edition for anything on one of the dashboards was not detected, this was caused because the obj we use for the dashboard structure is the same for the settings and the dashboard display. Since they reference the same thing any cooperation wasn't doing anything. For now, it has been fixed by doing a dup of the dashboard structure so it can be compared.

One issue persists, dashboards modified on the settings are also modified on the dashboard, since it still uses the same obj, reloading the page loads the correct structure (saved one).

## Useful links

- [AB#80331](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/80331)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [x] Modified any dashboard widget on a tab widget and close the modal without saving, a warning message is displayed

## Screenshots

Recording 2023-11-23 123744

# Checklist:

( * == Mandatory ) 

- [x] * I have set myself as assignee of the pull request
- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [x] * I have commented my code, particularly in hard-to-understand areas
- [x] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# More explanation
https://www.loom.com/share/05a716d61b9744faaf51fb304c21d1e5?sid=f87cf896-582a-4f76-93ae-8ceed801b145

### CODE REVIEW

**Comment by Maximo-reliefapps** [comment]
@AntoineRelief I'm marking the ticket as done, but there is still a bug with the edition of dashboards inside the tab widget.
The state of the settings dashboard is maintained between editions, and in the case of a second tab it's also edited on the parent dashboard

**Comment by AntoineRelief** [comment]
@Maximo-reliefapps 
Did you try to fix it?

**Comment by Maximo-reliefapps** [comment]
@AntoineRelief
I had a look but didn't fix it. I need to work on something else today.

**Comment by AntoineRelief** [comment]
Okay!

**Comment by AntoineRelief** [comment]
@Maximo-reliefapps 
found a simpler solution there:
https://github.com/ReliefApplications/ems-frontend/commit/8395a71c2547d3985e462631b4b6d65a510ce534

**Pull request closed without merging**
