### PR TITLE
refactor/AB#76713_change-fa-icons-display-as-svg

### PR DESCRIPTION
**Pull request by unai-reliefapp**
feat: replace whole fontawesomelibrary with only the icons we used and setting programatically the icon definitions and render in order to make the icons work in light and shadow dom
feat: add a mapper to transform any previously saved font awesome icons of v4 into the equivalent icon in v6 
feat: add sanitize html pipe in order to render fontawesome svgs in the html template safely 
refactor: replace all font awesome icon rendering by class with the new methods in all the application places where it's used. 
refactor: remove iconDisplayPipe as it's not needed anymore refactor: delete no more needed fontawesome web fonts as we are using svg now

# Description

In order to render font awesome icons easily in any kind of DOM(light or shadow) and to keep the icon list and features up to date(we had fontawesome icon list of v4 even if we had v6 installed, where some icons from v4 have to be mapped into their equivalent for v6), new methods have been created to render the icons as svg, which are DOM agnostic, and keeping the same features as before but with an updated list of icons to v6, and taking care of any previously saved configuration using v4 icon names.

Webfonts are not needed anymore as we are rendering font awesome icons as svg elements

## Useful links

- Please insert link to ticket
- [Side by side comparision between svg and pseudo element rendering](https://fontawesome.com/docs/web/dig-deeper/webfont-vs-svg#svg-js)

## Type of change

Please delete options that are not relevant.

- [X] Improvement (refactor or addition to existing functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please refer to screenshots below

## Screenshots

Same behavior in lightdom:
image

Updated icon list
image
image

Inline update:
https://github.com/ReliefApplications/ems-frontend/assets/123092672/d9a6e89a-56e6-407b-98c7-35a4b9e29749

Icons rendered also in shadow dom without problems
image

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings

### CODE REVIEW

**Comment by AntoineRelief** [comment]
@unai-reliefapp 
it's marked as drafts
should I go with review?

**Comment by unai-reliefapp** [comment]
> @unai-reliefapp it's marked as drafts should I go with review?

Hi @AntoineRelief , yes please, in order to make the fa icons work in the shadow dom for the embedded application the solution to render them as svgs is good and DOM agnostic, plus also we use the latest version of icons list

As it's a mayor change by itself I rather open a separate PR so you can check it first and if it's okay keep on with the application web component, that's why is open as draft, you can have a first look and after that i'll update it 👍

**Comment by AntoineRelief** [comment]
> > @unai-reliefapp it's marked as drafts should I go with review?
> 
> Hi @AntoineRelief , yes please, in order to make the fa icons work in the shadow dom for the embedded application the solution to render them as svgs is good and DOM agnostic, plus also we use the latest version of icons list
> 
> As it's a mayor change by itself I rather open a separate PR so you can check it first and if it's okay keep on with the application web component, that's why is open as draft, you can have a first look and after that i'll update it 👍 

Okay! Will do that
Thanks for seperating the code in multiple PRs

**Comment by unai-reliefapp** [comment]
@AntoineRelief Closed this one for the one with the correct branch name: https://github.com/ReliefApplications/ems-frontend/pull/1972

**Pull request closed without merging**
