### PR TITLE
feat/AB#105501_EIS-improve-multifile-display-in-grids

### PR DESCRIPTION
**Pull request by unai-reliefapp**
# Description

feat: add new display for multiple files in the grid component 
fix: grid edition on mode on click in file for download 
feat: add new closeOnClick property to close ui menu on element click

## Useful links

- [Link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/105501)

## Type of change

Please delete options that are not relevant.

- [X] Improvement (refactor or addition to existing functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [ ] Test A
- [ ] Test B

## Screenshots

image
image

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# More explanation
https://www.loom.com/share/05a716d61b9744faaf51fb304c21d1e5?sid=f87cf896-582a-4f76-93ae-8ceed801b145

### CODE REVIEW

**Comment by unai-reliefapp** [comment]
@AntoineRelief , french translation missing
Change done in the ui menu component is totally save, input has a default value, therefor the rest of the menus in the app previous to this change would work as expected 👍

**Comment by AntoineRelief** [comment]
@unai-reliefapp 

perhaps one quick change could be to indicate the number of files
Some text like:

"{number} files"

**Comment by unai-reliefapp** [comment]
> @unai-reliefapp
> 
> perhaps one quick change could be to indicate the number of files Some text like:
> 
> "{number} files"

Updated @AntoineRelief 👍

**Comment by AntoineRelief** [comment]
@unai-reliefapp 

just update the alignment of text in buttons, but working fine 👍

**Pull request merged**
