### PR TITLE
feat/AB#78061-cdk-portal-for-widgte-widget-in-ExpandedWidgetComponent

### PR DESCRIPTION
**Pull request by estelafs**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Useful links

- Please insert link to ticket: https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/78061
- Please insert link to back-end branch if any
- Please insert any useful link ( documentation you used for example )

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [ ] Test A
- [ ] Test B

## Screenshots

Please include screenshots of this change. If this issue is only back-end related, and does not involve any visual change of the platform, you can skip this part.

# Checklist:

( * == Mandatory ) 

- [ ] * I have set myself as assignee of the pull request
- [ ] * My code follows the style guidelines of this project
- [ ] * Linting does not generate new warnings
- [ ] * I have performed a self-review of my own code
- [ ] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [ ] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [ ] * My changes generate no new warnings
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by unai-reliefapp** [comment]
@AntoineRelief I pushed all the changes related the cdk portal and it's working fine. Still not finished, the only thing I'm concern is the delete button in the widget header. I hide the expand button when the widget is inside the expand modal for sure, but should we hide the delete button also and just keep the style, settings, etc. features?

Or should be able to delete a widget from the expanded dialog? If that's the case it's tricky logic implementation I think, if not I'll push one last commit hidding also the delete button on expanded widget dialog

cc @estelafs 
KR, Unai

**Comment by AntoineRelief** [comment]
> @AntoineRelief I pushed all the changes related the cdk portal and it's working fine. Still not finished, the only thing I'm concern is the delete button in the widget header. I hide the expand button when the widget is inside the expand modal for sure, but should we hide the delete button also and just keep the style, settings, etc. features?
> 
> Or should be able to delete a widget from the expanded dialog? If that's the case it's tricky logic implementation I think, if not I'll push one last commit hidding also the delete button on expanded widget dialog
> 
> cc @estelafs 
> KR, Unai

I think you can hide all buttons about édition/ deletion / styling / moving 👍

**Comment by unai-reliefapp** [comment]
> > @AntoineRelief I pushed all the changes related the cdk portal and it's working fine. Still not finished, the only thing I'm concern is the delete button in the widget header. I hide the expand button when the widget is inside the expand modal for sure, but should we hide the delete button also and just keep the style, settings, etc. features?
> > Or should be able to delete a widget from the expanded dialog? If that's the case it's tricky logic implementation I think, if not I'll push one last commit hidding also the delete button on expanded widget dialog
> > cc @estelafs
> > KR, Unai
> 
> I think you can hide all buttons about édition/ deletion / styling / moving 👍

Very nice then

**Comment by unai-reliefapp** [comment]
@AntoineRelief cdk portal finished and rearrange any needed output events from the dom portal insertion 👍 

I also added some subscription clear logic from the workflow components on activating child routes 👍 
cc @estelafs

**Comment by AntoineRelief** [comment]
@unai-reliefapp 
I also removed some useless properties + instead of using the expandedWidgetRef property to hide or show adorners, doing that directly in the widget, based on a new property "fullscreen"

**Pull request merged**
