### PR TITLE
Feat/ab#67236 db new widget layout solution angular gridster

### PR DESCRIPTION
**Pull request by unai-reliefapp**
# Description

Replaced kendo grid layout system with the angular-gridster package

## Useful links

- Please insert link to ticket
- [Useful link](https://github.com/tiberiuzuld/angular-gridster2)

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [ ] Test A
- [ ] Test B

## Screenshots

image
image
image

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings

### CODE REVIEW

**Comment by unai-reliefapp** [comment]
@AntoineRelief We are using the kendo-tilelayout header in some places in the application like summary-card or map component(mostly widgets), but now that the kendo tile layout is gone should go keep those, or replace them with another header with same styling?

That way we can delete the @progress/kendo-angular-layout package, but i did not delete it yet just in case

KR, Unai

**Comment by AntoineRelief** [comment]
> @AntoineRelief We are using the kendo-tilelayout header in some places in the application like summary-card or map component(mostly widgets), but now that the kendo tile layout is gone should go keep those, or replace them with another header with same styling?
> 
> That way we can delete the @progress/kendo-angular-layout package, but i did not delete it yet just in case
> 
> KR, Unai

If possible styling should remain the same indeed
( would it be for widgets or for the widget grid )

**Comment by unai-reliefapp** [comment]
> > @AntoineRelief We are using the kendo-tilelayout header in some places in the application like summary-card or map component(mostly widgets), but now that the kendo tile layout is gone should go keep those, or replace them with another header with same styling?
> > That way we can delete the @progress/kendo-angular-layout package, but i did not delete it yet just in case
> > KR, Unai
> 
> If possible styling should remain the same indeed ( would it be for widgets or for the widget grid )

There are some components that have a styling but that are used for the layout grid system of kendo, so now that it's out, maybe we can take out those components, and add some divs with a border and styling, same as the ones of the kendo component but just html, without using now the kendo layout components

PD: I'll update the grid styles and replacement later

**Comment by unai-reliefapp** [comment]
@AntoineRelief things missing:

- With the new layout ngoninit component is not triggered anymore, so i have to check that content is updated properly on settings update
- check border styling applied on show widget border
- some issue with the styling sidenav from floating options in the widget

KR, Unai

**Comment by unai-reliefapp** [comment]
Close, please refer to this [PR](https://github.com/ReliefApplications/oort-frontend/pull/1883)

**Pull request closed without merging**
