### PR TITLE
feat/AB#80613_edit-refData-fields

### PR DESCRIPTION
**Pull request by matheus-relief**
# Description

This PR includes changes needed to be possible to add and edit reference data fields.

## Useful links

- Please insert link to ticket: https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/80613

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

See below

## Screenshots

Peek 2023-08-30 03-01

# Checklist:

( * == Mandatory ) 

- [x] * I have set myself as assignee of the pull request
- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [x] * I have commented my code, particularly in hard-to-understand areas
- [x] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# More explanation
https://www.loom.com/share/05a716d61b9744faaf51fb304c21d1e5?sid=f87cf896-582a-4f76-93ae-8ceed801b145

### CODE REVIEW

**Review by unai-reliefapp — COMMENTED** [review]
Hi @matheus-relief 
Only thing, should we have the option to edit already set fields for static reference data? 
image

Linked ticket does not specify, looks like it has to be a generic feature, but idk.

And another thing, but just from the UX point of view, maybe cancel inline edition on clicking outside of the row? @AntoineRelief 

Otherwise looks great to me, clever use of row edition with a single form control and not a form array 👍

**Comment by AntoineRelief** [comment]
> Hi @matheus-relief Only thing, should we have the option to edit already set fields for static reference data? image
> 
> Linked ticket does not specify, looks like it has to be a generic feature, but idk.
> 
> And another thing, but just from the UX point of view, maybe cancel inline edition on clicking outside of the row? @AntoineRelief
> 
> Otherwise looks great to me, clever use of row edition with a single form control and not a form array 👍

@unai-reliefapp 
yes for the inline edition that can cancel indeed
+ no need for the static one, as the structure is from a csv
the errors mostly come from payload data

**Comment by unai-reliefapp** [comment]
> > Hi @matheus-relief Only thing, should we have the option to edit already set fields for static reference data? image
> > Linked ticket does not specify, looks like it has to be a generic feature, but idk.
> > And another thing, but just from the UX point of view, maybe cancel inline edition on clicking outside of the row? @AntoineRelief
> > Otherwise looks great to me, clever use of row edition with a single form control and not a form array 👍
> 
> @unai-reliefapp yes for the inline edition that can cancel indeed
> 
> * no need for the static one, as the structure is from a csv
>   the errors mostly come from payload data

I can add the cancel on clicking outside to the PR @matheus-relief

**Comment by unai-reliefapp** [comment]
Added click outside feature in the last commit @AntoineRelief 

Video ref:
https://github.com/ReliefApplications/ems-frontend/assets/123092672/90d13c08-b77a-4852-956d-fae50d6fd7a2

**Review by unai-reliefapp — APPROVED** [review]

**Comment by AntoineRelief** [comment]
@unai-reliefapp @matheus-relief 
all good, good work guys

**Pull request merged**
