### PR TITLE
AB#96347, AB#96226, AB#96350, AB#92816 - Email Notifications

### PR DESCRIPTION
**Pull request by HasnatL-Adapptlimited**
# Description

Implemented more QA Email Fixes

## Tickets

- [ ] https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/96347/
- [ ] https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/96226/
- [ ] https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/96350/
- [ ] https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/92816/

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by HasnatL-Adapptlimited** [comment]
Hey @AntoineRelief 

PR has been raised

CC: @Vaishali1709 @morgang-adappt

**Comment by AntoineRelief** [comment]
@HasnatL-Adapptlimited @morgang-adappt 

the code is not running fine, as there is one property that doesn't exist but is being used in one of the components

I guess the change should be something like:
  public allFields: any[] = [];
or
  public allFields: FieldStore[] = [];

in the email-template file but please confirm

Also, please, for future PRs ( or if you can even for this one ), try to explain a bit the changes in the description of the PR

some of the files are now more than 1200 lines long, it's not so easy to understand the changes

cc @Vaishali1709

**Comment by HasnatL-Adapptlimited** [comment]
> @HasnatL-Adapptlimited @morgang-adappt
> 
> the code is not running fine, as there is one property that doesn't exist but is being used in one of the components
> 
> I guess the change should be something like: public allFields: any[] = []; or public allFields: FieldStore[] = [];
> 
> in the email-template file but please confirm
> 
> Also, please, for future PRs ( or if you can even for this one ), try to explain a bit the changes in the description of the PR
> 
> some of the files are now more than 1200 lines long, it's not so easy to understand the changes
> 
> cc @Vaishali1709

Hey @AntoineRelief  any[] would be more appropriate in this case

**Comment by AntoineRelief** [comment]
@HasnatL-Adapptlimited @morgang-adappt @Vaishali1709

just merged the branch, with some small changes + fix for the build to work

I'll push it on UAT after the call

**Comment by HasnatL-Adapptlimited** [comment]
Hey @AntoineRelief,
 
Thank you so much for reviewing!
 
We just have 1 more push as we noticed 1 small issue, we will open a PR within 1 hour
 
CC: @morgang-adappt @Vaishali1709

**Pull request merged**
