### PR TITLE
feat/AB#75323_map-last-update-control

### PR DESCRIPTION
**Pull request by estelafs**
# Description
Added to the map controls the "Last updated on" control, displaying the last time the map was refreshed (using the getLayers() method from the map component to get the correct time)

## Useful links

- Please insert link to ticket: https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/75323

## Type of change
- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Add the control to a map widget and everytime the maps loads, (at init, with the dashboard filters updates etc) watch the update control display the time of the action.

## Screenshots
[controls.webm](https://github.com/ReliefApplications/ems-frontend/assets/28535394/2379333b-4603-466c-9c10-0952fcc0656a)
[map.webm](https://github.com/ReliefApplications/ems-frontend/assets/28535394/42b5b71e-ea2d-4687-820d-875eb1c57973)

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AntoineRelief** [comment]
@estelafs 
Almost all good
the only issues I could find:
- if you edit the control, it is not reflected in the map directly ( even if you have one or more layers ). The control remains on its default position
- try to make it smaller, it takes too much space at the moment

**Comment by unai-reliefapp** [comment]
> @estelafs Almost all good the only issues I could find:
> 
> * if you edit the control, it is not reflected in the map directly ( even if you have one or more layers ). The control remains on its default position
> * try to make it smaller, it takes too much space at the moment

Taking this fixes @estelafs 

@AntoineRelief About the second point: 

- Text displayed in the last updated control can be edited with less words? 
- By small you mean for example set a max-width and wrap the text content in two lines or one for each data type? e.g.
image

KR, Unai

**Comment by AntoineRelief** [comment]
> > @estelafs Almost all good the only issues I could find:
> > 
> > * if you edit the control, it is not reflected in the map directly ( even if you have one or more layers ). The control remains on its default position
> > * try to make it smaller, it takes too much space at the moment
> 
> Taking this fixes @estelafs
> 
> About the second point:
> 
> * Text displayed in the last updated control can be edited with less words?
> * By small you mean for example set a max-width and wrap the text content in two lines or one for each data type? e.g.
>   image
> 
> KR, Unai

I think like that it just takes too much space
perhaps it could be an icon, and when you hover, it expands
or, reduce the text size & padding
A single row is fine

**Comment by unai-reliefapp** [comment]
> > > @estelafs Almost all good the only issues I could find:
> > > 
> > > * if you edit the control, it is not reflected in the map directly ( even if you have one or more layers ). The control remains on its default position
> > > * try to make it smaller, it takes too much space at the moment
> > 
> > 
> > Taking this fixes @estelafs
> > About the second point:
> > 
> > * Text displayed in the last updated control can be edited with less words?
> > * By small you mean for example set a max-width and wrap the text content in two lines or one for each data type? e.g.
> >   image
> > 
> > KR, Unai
> 
> I think like that it just takes too much space perhaps it could be an icon, and when you hover, it expands or, reduce the text size & padding A single row is fine

@AntoineRelief Added fixes to the PR, video showing feature(there is a padding left in the text in the commit that it's not shown in the video):

https://github.com/ReliefApplications/ems-frontend/assets/123092672/3e2d70a3-1242-480c-8bbc-124b37d457fb

The chosen icon it's just an example, you can set whatever icon you need in the last update method and it would be good to go 👍

**Comment by AntoineRelief** [comment]
perfect, thanks @unai-reliefapp !

**Pull request merged**
