### PR TITLE
feat/OORT-657_add-workflow-context

### PR DESCRIPTION
**Pull request by matheus-relief**
# Description

This PR adds the possibility to use values from selected records in a grid to fill fields of a form if inside a workflow.
In order to do this, two new custom functions were added: 
* elementAt: Get nth element of an array 
*  getWorkflowContext: Given the id of the workflow and of the widget, returns the selected records when the Next/Previous step action button was clicked 

## Useful links

[Add workflow context](https://oortcloud.atlassian.net/jira/software/projects/OORT/boards/3?selectedIssue=OORT-657)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

* Create a workflow
* Create dashboard page in it (id: `64d135634c9d322ffbdad297`)
* Add a grid widget, with an action to go to next step (id: `0`)
* Create form and add to the following step of the workflow
* On the form builder, create a resource question using the same resource setup in the grid added
* Set its default value to `elementAt(getWorkflowContext("64d135634c9d322ffbdad297", 0), 0)`

## Screenshots

Peek 2023-07-12 11-40

# Checklist:

( * == Mandatory ) 

- [x] * I have set myself as assignee of the pull request
- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [x] * I have commented my code, particularly in hard-to-understand areas
- [x] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by unai-reliefapp** [comment]
@matheus-relief Just wondering, did you use the 2.1.x-oort branch as base branch to create this one? It looks like the commit list is coming from somwhere else

**Comment by matheus-relief** [comment]
Hey @unai-reliefapp ! I did use 2.1.x-oort as base, but also merged 2.1.x into it. Not sure what is best practice in this case, have two separate PRs, what do you think?

**Comment by unai-reliefapp** [comment]
Hi @matheus-relief , I guess that Antoine would have to first merge 2.1.x into 2.1.x-oort.
The target branch of the ticket is set as 2.1.x, my recommendation would be to stick to that base branch.

Double check with him just in case, but if the base branch is 2.1.x, then it's time for cherry picking!

**Comment by matheus-relief** [comment]
@unai-reliefapp oops that’s my bad, it should be 2.1.x-oort, I’ll create the tag on Jira

**Comment by unai-reliefapp** [comment]
> 

Best approach then I'll say that first merge `2.1.x` branch into `2.1.x-oort` and after that merge this PR into `2.1.x-oort`.
That way we know what is merged in this exact commit, and also because the aim of this PR is not to update `2.1.x-oort` with the `2.1.x` base 😄 , even if we have to

Double check with Antoine anyway, I guess that he is accountable of what/how version should be updated

**Pull request closed without merging**
