### PR TITLE
Fix: Pagination on choose record modal for attach to record button

### PR DESCRIPTION
**Pull request by matheus-relief**
# Description

This PR fixes the issue with pagination on the choose record modal.

Removed most of the logic on the component, letting the `graphql-select` and the `safe-core-grid `components handle the pagination internally. 

Few notable changes:
* The `graphql-select` now checks the input query to see if it's supposed to use the `first` of `afterCursor` approach when dealing with pagination
* When opening the `graphql-select`'s select, the search bar will be focused automatically

## Ticket
[ABC - Attach to record action should use graphql-select and not classic select ( pagination not working )](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/69369)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

* See bellow
* Also tested some other places that use graphql-select to check if queries that use afterCursor continue to work fine

## Screenshots
Peek 2023-07-12 11-40

# Checklist:

( * == Mandatory ) 

- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have commented my code, particularly in hard-to-understand areas
- [x] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by estelafs — APPROVED** [review]
I just handled the conflicts, everything is working fine!

**Comment by taylordardono** [comment]
@AntoineRelief Does this PR have to switch to the last 2.0.x as new base branch?

**Comment by unai-reliefapp** [comment]
@AntoineRelief Does this PR have to switch to the last version of 2.0.x as base branch?

**Comment by AntoineRelief** [comment]
@unai-reliefapp 
Yes

**Comment by AntoineRelief** [comment]
@matheus-relief 
cc @estelafs 
all working fine 👍 
looks quite better like that !

**Pull request merged**
