### PR TITLE
AB#84099 - Pagination for reference data loads new data when changing page

### PR DESCRIPTION
**Pull request by guisoares1**
# Description

Fixed situations:
- Reference data configured for non-paginated, summary card paginated, last page behaves incorrectly.
- If the reference data is configured for paginated and summary card paginated, the last page behaves incorrectly.
## Useful links
- [Link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/84099)

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [X] Added a graphql reference data to a summary card and observed pagination behavior.

## Screenshots

https://github.com/ReliefApplications/ems-frontend/assets/55603259/f66377c8-089b-411a-b751-11367c664792

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# More explanation
https://www.loom.com/share/05a716d61b9744faaf51fb304c21d1e5?sid=f87cf896-582a-4f76-93ae-8ceed801b145

### CODE REVIEW

**Review by RenzoPrats — APPROVED** [review]
It's working fine, looks good to me!

**Comment by AntoineRelief** [comment]
still see some issues:

Capture d’écran 2024-01-25 à 15 25 09

**Comment by AntoineRelief** [comment]
@guisoares1 @RenzoPrats 
cc @matheus-relief in case you need help

that's still not working fine and I really need that quickly, so whoever feel the most confortable with it can take it

the issues I'm facing
- if you have a ref data without totalCount field set, and you reach the end of the list, you can still continue to load next page, and so, you will load an empty page, which does not make sense. When you go back to first page, you will see empty items, and I don't want that

**Comment by AntoineRelief** [comment]
@guisoares1 
should now be working
there was an error with the finalPage, as you would not revert it when refreshing the view
also, I removed all the logic about disableNext, because if you pass the length to the paginator, it will automatically be able to identify that the next should be disabled

**Pull request merged**
