### PR TITLE
feat/AB#63175_ABC-Implement-UI-Icon-Component

### PR DESCRIPTION
**Pull request by Bricecrx**
# Description

With this ticket, all mat-icon call by the application is replaced with ui-icon call. MatIconModule calls are also deleted and replaced every time it is needed.

## Ticket

I can't paste the azure ticket link because I do not have access to Azure. Here is the ticket id however : [AB#63175](https://dev.azure.com/WHOHQ/2888b816-2d79-49ef-a86e-561e6cd456a0/_workitems/edit/63175)

## Type of change

- [x] Improvement (refactor or addition to existing functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

It has been tested through navigation within the application and verification of replacements

## Screenshots

a
image
image
b

# Checklist:

( * == Mandatory ) 

- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have commented my code, particularly in hard-to-understand areas
- [x] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings

### CODE REVIEW

**Comment by unai-reliefapp** [comment]
Please delete the safeicon element from safe library. We should use the new ui-icon directly from the UI library.
Also double check which icons are used as ui-button icons as for example here:
image

or if the safe-icon contains a `(click)` event attached, in which that case you should use the `ui-button` with the `isIcon` param in true

Also please double check all styling related to mat-icon or safe-icon and remove it

**Comment by Bricecrx** [comment]
Still have to deal with select menus in form fields (the directive does not take them into account for now, but we are waiting for select component to be merged in order to change that)

**Comment by Bricecrx** [comment]
Need to check if elements combining uiPrefix/Suffix directives and ngIf directives are working well (after uiFormField directive modification is merged)

**Comment by unai-reliefapp** [comment]
Too many conflicts, have to be re done, closed

**Pull request closed without merging**
