### PR TITLE
Feat 2.1.x/ab#74392 finalize tabs widgets

### PR DESCRIPTION
**Pull request by Maximo-reliefapps**
## ⚠️ TO-DO - Missing work
- [x] Understand why the maps are not loading as expected and substitute the timeouts for with an specific solution.
- [x] Fix overlap of tabs and the drag icon on the dashboards.
- [x] Improve overflow sidebar so it only wraps the tab dashboard content, currently it also affects the title (& other stuff in the settings)

# Description

Improved some stuff for the new tab widget, what has been done: 
- Added a custom .svg icon for the widget + a custom color.
- Set a timeout so the maps can load inside a tab (temp fix).
- Load each tab only when displayed.
- When deleting a tab go back to the previous one automatically.

## Useful links

- [#74392 finalize tabs widgets](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/74392)

## Type of change

- [x] Improvement (refactor or addition to existing functionality)

# How Has This Been Tested?

- [x] Used the tab widget on dashboard with multiple maps and make sure everything works and shows as expected.
- [x] Delete a tab in the widget settings and check that we aren't stuck on the deleted tab anymore. 

## Screenshots

Screenshot from 2023-09-06 16-52-00

# Checklist:

( * == Mandatory ) 

- [x] * I have set myself as assignee of the pull request
- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [ ] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [x] * I have commented my code, particularly in hard-to-understand areas
- [x] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings
- [x] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by NathanHGit** [comment]
I proposed a solution to the map loading problem, I haven't found a better way to do it. The problem is related to the rendering of the map view. The `ngAfterViewInit` event is called before the coponent is fully rendered. I looked on the web and it seems that the problem is recurrent. I used `ngAfterContentChecked` which is called every time something changes in the DOM. I added a boolean to define if the component is loaded. The aim is to limit the loss of time as the event is called several times.

**Comment by NathanHGit** [comment]
I tried to fix the last two items of the missing work list. Both are because tab title and tab content are linked in the dom. I tried using ng-template to split them but I couldn't implement it correctly. 

I managed to fix the scrolling bar that was overlapping the tab title with some CSS properties. However, I couldn't to fix the overlap issue between the tab title and the widget header icons. I also had a look in the tabs widget settings, but I couldn't find a suitable solution either. The structure of the angular tab element is very restrictive in some ways.

**Comment by RenzoPrats** [comment]
I tested the changes done and seems to be working correctly, about the missing work it seems to be related to style but I was not able to see/test any of this issues, maybe should be validated this part of ticket and then check if is really necessary to fix something in the styles.

**Review by RenzoPrats — CHANGES_REQUESTED** [review]
I tested the changes done and seems to be working correctly. About the missing work it seems to be related to style, I tested it and indeed we still having issues like in the images below 
Captura de tela de 2023-09-18 13-59-11
Captura de tela de 2023-09-18 13-58-08

We could validate the work done, but it will require some fix in the style.

**Comment by unai-reliefapp** [comment]
@AntoineRelief @Maximo-reliefapps Video showing fixed overflows plus keeping current animation behavior of the tab animations

https://github.com/ReliefApplications/oort-frontend/assets/123092672/1d787a44-72f3-4b92-9d3d-a471dd9246fb

**Comment by AntoineRelief** [comment]
@unai-reliefapp @Maximo-reliefapps 
closing this one
duplicated some of the changes there:
https://github.com/ReliefApplications/ems-frontend/commit/e3d911870f3f664890ef5a885d24e1cc062370bf

I found a cleaner way to fix the map issue + prevent tabs to be loaded if not displayed

**Pull request closed without merging**
