### PR TITLE
AB#83334_change_modern_filter_styling

### PR DESCRIPTION
**Pull request by MwanPygmay**
# Description

Changed padding left for filters, and added a vertical alignment so that all questions are on the same line. For the filter to look good, I also changed configuration and updated width of 'Emergencies' and boolean question from the **Layout** config.
/!\ Did not do the toggle with labels outside part, tried some stuff using css, but everytime you change too much the css, surveyjs changes the toggle to a radiogroup.

## Useful links

- [Please insert link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/83334/)

## Type of change

Please delete options that are not relevant.

- [x] Improvement (refactor or addition to existing functionality)

# How Has This Been Tested?

Looked at styling with the filter from SUI.
Use following JSON:
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "grade",
     "visible": false,
     "title": "grade",
     "valueName": "grade",
     "defaultValue": " "
    },
    {
     "type": "html",
     "name": "question1",
     "width": "120px",
     "minWidth": "120px",
     "startWithNewLine": false,
     "valueName": "question1",
     "html": "<div style=\"height: 100%; vertical-align: middle; color: #00205C;\"><b>Emergencies</b></div>"
    },
    {
     "type": "boolean",
     "name": "isactive",
     "width": "210px",
     "minWidth": "210px",
     "startWithNewLine": false,
     "titleLocation": "hidden",
     "valueName": "isactive",
     "defaultValue": "true",
     "labelTrue": "Active",
     "labelFalse": "Inactive"
    },
    {
     "type": "tagbox",
     "name": "regions",
     "startWithNewLine": false,
     "title": "Region",
     "titleLocation": "left",
     "valueName": "regions",
     "placeholder": "Select Regions",
     "referenceData": "65ae66820ef1e4097f532a6a",
     "referenceDataDisplayField": "name"
    },
    {
     "type": "tagbox",
     "name": "countries",
     "startWithNewLine": false,
     "titleLocation": "left",
     "valueName": "countries",
     "placeholder": "Select Countries",
     "referenceData": "656f095471299fd0be2482bd",
     "referenceDataDisplayField": "name",
     "isPrimitiveValue": false
    },
    {
     "type": "text",
     "name": "start_date",
     "startWithNewLine": false,
     "title": "Time Range",
     "titleLocation": "left",
     "valueName": "start_date",
     "inputType": "date"
    },
    {
     "type": "text",
     "name": "end_date",
     "startWithNewLine": false,
     "title": "To",
     "titleLocation": "left",
     "valueName": "end_date",
     "inputType": "date"
    }
   ]
  }
 ],
 "showQuestionNumbers": "off"
}

## Screenshots

Screenshot from 2024-01-24 10-46-51

# Checklist:

( * == Mandatory ) 

- [x] * I have set myself as assignee of the pull request
- [ ] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [ ] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AntoineRelief** [comment]
@NathanHGit are you still doing the review or is it all good?

**Comment by NathanHGit** [comment]
@AntoineRelief I am still working on it. I made some changes to make the behavior more generic. I was looking for the toggle design now. I can push my changes if you want

**Comment by AntoineRelief** [comment]
> @AntoineRelief I am still working on it. I made some changes to make the behavior more generic. I was looking for the toggle design now. I can push my changes if you want

all good, I was just wondering as you started the review some hours ago if I should go for it or not

**Comment by NathanHGit** [comment]
@MwanPygmay @AntoineRelief I refactored the code. 

We were overwritting the following question css property `padding-left: var(--sd-base-padding);` by setting it to 10px. The issue is that this variable is not exclusive to the element, causing the questions to shift to the left (see below).
`width: calc(100% + var(--sd-base-padding));`
`margin-left: calc(-1*var(--sd-base-padding));`
Moreover, the more questions added, the more the shift was important. I rewrote the property for the parent to make it more generic. I kept the right padding to prevent the edit button from sticking to the last question.

I used `self-align` to align questions to the center of the parent div, which seems to be a cleaner solution. 

A margin was used to manually align to the center the question labels, while it worked for inputs, it didn't work for all questions. Then I used align-self center one again instead of using a determined number of pixels.

**Comment by NathanHGit** [comment]
@AntoineRelief  By centering everything, we get this kind of display. Is that ok ?

image

I also searched for the desired toggle display, but it seems to belong to an older version of SurveyJS.

**Comment by NathanHGit** [comment]
@AntoineRelief One more thing, since the CSS updates are designed for the modern display of the dashboard, the preview of the form does not use these changes.

image

**Comment by AntoineRelief** [comment]
@NathanHGit 
check with @MwanPygmay please

**Comment by NathanHGit** [comment]
@AntoineRelief My questions were discussed with @MwanPygmay. It is ready to be merged or reviewed once more for my changes

**Pull request merged**
