### PR TITLE
REBASE - Fix 2.0.x/ab#69129 filters not working

### PR DESCRIPTION
**Pull request by Maximo-reliefapps**
**Replicated [original PR](https://github.com/ReliefApplications/oort-frontend/pull/1633) commits from @RenzoPrats to 2.0**

# Description

Fixed issue with timezone when select a date to filter in grid. It was modified the date select accordingly to the timezone so when it's passed to the query it will be the value of was selected in the filter.

## Ticket

https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/69129

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

It has been tested verifying in the application if now the time passed to the query is the same of the one selected in the filter.

## Screenshots

Captura de tela de 2023-07-14 10-26-41
Captura de tela de 2023-07-14 10-26-22

# Checklist:

( * == Mandatory ) 

- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Maximo-reliefapps — COMMENTED** [review]
All good and working as expected
I created a new branch for the rebase since it was the easiest.

**Comment by NathanHGit** [comment]
Is it supposed to behave like this ? (there are 101 records sorted by date of birth ASC)

peek

**Comment by NathanHGit** [comment]
Is it supposed to act like this ? 

peek

**Comment by Maximo-reliefapps** [comment]
@NathanHGit The ticket consists on fixing the passed time for the filters, not changing the behavior for them, so I assume it's working as expected.
Previously the timezone was taken into account when setting a filter, which was causing some inconsistencies.

**Review by NathanHGit — APPROVED** [review]
Seems to work as expected regarding ticket scope.

**Review by NathanHGit — APPROVED** [review]
Seems to work as expected regarding ticket scope (this is a duplicate, I have some network issues)

**Comment by AntoineRelief** [comment]
@Maximo-reliefapps 
cc @NathanHGit 

I believe one thing is still not working, when we do filtering without opening the menu ( what we call "quick filter" )


Capture d’écran 2023-08-18 à 12 42 42

**Comment by NathanHGit** [comment]
I moved the logic one step above in order to act on all filter changes

**Comment by AntoineRelief** [comment]
@Maximo-reliefapps 
@NathanHGit 
all good 👍 
I only renamed the method to not only be about dates and removed a previous commit artifact in the code

**Pull request merged**
