### PR TITLE
Ab#88033 add styling for automation

### PR DESCRIPTION
**Pull request by MwanPygmay**
# Description

- Add missing translations
- Change styling for modals
- Add drag and drop
- Add types and apply them

## Useful links

- [Please insert link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/88033)

## Type of change

Please delete options that are not relevant.

- [x] Improvement (refactor or addition to existing functionality)

# How Has This Been Tested?

Go into any automation module.

## Screenshots

Please include screenshots of this change. If this issue is only back-end related, and does not involve any visual change of the platform, you can skip this part.
image
image

# Checklist:

( * == Mandatory ) 

- [x] * I have set myself as assignee of the pull request
- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [x] * I have commented my code, particularly in hard-to-understand areas
- [x] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# More explanation
https://www.loom.com/share/05a716d61b9744faaf51fb304c21d1e5?sid=f87cf896-582a-4f76-93ae-8ceed801b145

### CODE REVIEW

**Comment by unai-reliefapp** [comment]
Hi @MwanPygmay 
Some suggestions(let's see what @Matthis-M-ReliefApps thinks about them)
- In this modal, add a cursor pointer to each options plus a little gray shadow on hover so the user knows that are clickable and keep a better UX for him/her
image
- The actions affect specific objects, In order to improve the UX for the user and make sure that has a clear overview of what the rule is doing by just looking at the actions, I'll suggest to add the target of the action next to the action itself, e.g.
For this config:
image
This display:
image
You'll have to change a little bit the logic to include the label also with the value of the target
- Add translations also in the action modal title:
image

**Comment by Matthis-M-ReliefApps** [comment]
All are good suggestions, thanks Unai!!

**Comment by MwanPygmay** [comment]
Applied your suggested changes @unai-reliefapp + refactor.
For the target of the action, I put the name of the widget rather than the name of the layers (was way easier to code), I can change it if it is more relevant!
image

**Comment by unai-reliefapp** [comment]
> Applied your suggested changes @unai-reliefapp + refactor. For the target of the action, I put the name of the widget rather than the name of the layers (was way easier to code), I can change it if it is more relevant! image

I know, you'll have to update what information is saved(not just id but related name also), it should be much helpful to know what layer is applied or what tab is opened in the action, but @Matthis-M-ReliefApps  has the last word

**Comment by MwanPygmay** [comment]
@unai-reliefapp @Matthis-M-ReliefApps  now getting name of layers/tabs/widget 
image

**Comment by AntoineRelief** [comment]
> @unai-reliefapp @Matthis-M-ReliefApps now getting name of layers/tabs/widget image

@MwanPygmay 
one issue with that is we only see the names when editing the component, not when seeing the list of components of an existing rule for example

**Pull request merged**
