### PR TITLE
fix: Keeping current map state when filtering layers with dashboard filters

### PR DESCRIPTION
**Pull request by matheus-relief**
# Description

This PR changed the map component so it keeps the current state (zoom + layers visibility) when applying dashboard filters

## Ticket
[Please insert link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/66070/)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

See bellow

## Screenshots
Peek 2023-05-29 13-51

# Checklist:

( * == Mandatory ) 

- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have commented my code, particularly in hard-to-understand areas
- [x] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AntoineRelief** [comment]
@matheus-relief unfortunately it's not working in all cases

**Comment by AntoineRelief** [comment]
@matheus-relief 
I'm using shouldDisplay instead of visibility + I added close of the layer-control when triggering filtering
also, changed the logic to use overlayTree instead of this.layers property

**Comment by matheus-relief** [comment]
@AntoineRelief  Checked your changes and indeed looks way better, just curious about which cases my solution didn’t work for

**Comment by AntoineRelief** [comment]
@matheus-relief 
I think I got frustrated by the layer-control in fact, which would always break if it was kept active
But you removed that in a previous PR, so I found the fix after some time
I cannot say for sure what was wrong
but your PR really helped to structure the code I provided, thanks for that 👍 
( got a lot of issues this morning, I didn't take enough time to well comment the changes I did , sorry for that )

**Pull request merged**
