### PR TITLE
feat/AB#104622_EIS-selectionof-occurrence-in-properties-of-doc-upload

### PR DESCRIPTION
**Pull request by unai-reliefapp**
# Description

feat: integrate saved drive id from file question configuration into the file upload for cs documentation 
feat: integrate Related Occurrence category into file question configuration using occurrence type and occurrences list 
feat: integrate occurrences lists into the created cs-docs dropdown component

## Useful links

- [Link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/104622)

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [ ] Test A
- [ ] Test B

## Screenshots

https://github.com/user-attachments/assets/d588d355-c81e-4c14-9e48-fea5086f0166

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# More explanation
https://www.loom.com/share/05a716d61b9744faaf51fb304c21d1e5?sid=f87cf896-582a-4f76-93ae-8ceed801b145

### CODE REVIEW

**Comment by unai-reliefapp** [comment]
@AntoineRelief You'll see some strange checks of empty string in the code because they have an occurrence type with id 0 😮‍💨 
Let me know if how the data and what data is saved is valid for their requirements @AntoineRelief

**Comment by AntoineRelief** [comment]
@unai-reliefapp 

just about the naming, I don't think "drive<property>" is correct

we could just use "occurrence" & "occurrenceType"

the rest looks good

**Comment by unai-reliefapp** [comment]
> @unai-reliefapp
> 
> just about the naming, I don't think "drive" is correct
> 
> we could just use "occurrence" & "occurrenceType"
> 
> the rest looks good

Pushed changes plus fix the integration of OccurrenceType as a valid param in the upload request body(it was missing on this PR)
image
Now is also included

**Comment by AntoineRelief** [comment]
@unai-reliefapp 

I'll let you handle the merging of the last version of AB#74456 branch ( with document properties ), with this one, as I can see some conflicts

**Comment by unai-reliefapp** [comment]
ey @AntoineRelief , i was testing the merge and i got this error using their API

image

I can push the merge and you do the final check on it?

**Comment by AntoineRelief** [comment]
@unai-reliefapp 
I have the same error, I'll contact them

**Comment by AntoineRelief** [comment]
@unai-reliefapp 

putting back the ticket in todo

some elements I changed:
- there was no more default drive id, so upload would not work without a selected occurrence. I found how they query the default drive id, and added some code to get it when uploading files
- due to that, I moved the cs apollo client configuration to the service + added a callback so the token is taken from the local storage for each request, instead of doing it when initializing the client

Changes I'd like to see:
- instead of storing the driveId of the occurrence, we must store the id, and fetch the driveId just before uploading, using the id of the occurrence. The reason for this change is the id of the occurrence will never change, but I can't say for sure that the id of the drive will not change. In case it changes, the form is broken.
- after previous change is done, I'd also like to have an expression to set the occurrence:

Capture d’écran 2024-10-31 à 11 22 37

I'm pretty sure the expression to get the occurrence type is useless. Same as previous query, if you store the occurrence id, you can easily get the occurrencetype, and you should not be able to change the occurrence type dynamically, based on the form, as you may end up in a situation where the type would not be the same than the occurrence one

query to get the drive id & occurrencetype based on occurrence id

```
query GetOccurrence($id: String) {
  occurrence(id: $id) {
    id
    driveid
    occurrencetype
  }
}
```

**Pull request merged**
