### PR TITLE
AB#79776 Dashboard reorder and resize not workings

### PR DESCRIPTION
**Pull request by Maximo-reliefapps**
# Description

[AB#79453](https://dev.azure.com/WHOHQ/2888b816-2d79-49ef-a86e-561e6cd456a0/_workitems/edit/79453) changes wroke the dashboard auto-save function for reordering & resizing the widgets.
Reverting the code worked but introduced another bug with the tabs widget, where changing between tab displayed multiple animations.
The true arg from `this.setGridOptions()` was moved from the ngOnChanges to the ngOnInit. Auto scroll still works as expected.

## Useful links

- [AB#79453](https://dev.azure.com/WHOHQ/EMSSAFE/_boards/board/t/App%20Builder%20-%20Core/Stories?workitem=79776&text=maximo)
- [Conflicting PR](https://github.com/ReliefApplications/ems-frontend/pull/2086)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [x] Resize and reorder widgets on a dashboard, reloading the page maintains the state of the widgets.
- [x] Adding new widgets to a tab or a dashboard scrolls the page automatically to the bottom.

## Screenshots

ezgif com-video-to-gif

# Checklist:

( * == Mandatory ) 

- [x] * I have set myself as assignee of the pull request
- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [x] * I have commented my code, particularly in hard-to-understand areas
- [x] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# More explanation
https://www.loom.com/share/05a716d61b9744faaf51fb304c21d1e5?sid=f87cf896-582a-4f76-93ae-8ceed801b145

### CODE REVIEW

**Comment by AntoineRelief** [comment]
@Maximo-reliefapps 
I think you linked it to another ticket ;) 
I just changed it to appear on devops

**Review by estelafs — COMMENTED** [review]
Working as expected.

@AntoineRelief Just to confirm that this could be caused by something recently merged into the branch that updates the dahsboard steps in the wokflows and not a new inconsistent error: when entering dashboard steps for the first time, the editDashboard mutation is triggered 

[Screencast from 23-11-2023 11:45:48.webm](https://github.com/ReliefApplications/ems-frontend/assets/28535394/b843d1d3-1202-4936-a4ad-a54fcad28424)

[Screencast from 23-11-2023 12:01:53.webm](https://github.com/ReliefApplications/ems-frontend/assets/28535394/6cd961a0-f1bf-4d60-815f-06960448d0b3)

This one is no only in the first time the dashboard step inits but it has style to apply:
[Screencast from 23-11-2023 11:51:22.webm](https://github.com/ReliefApplications/ems-frontend/assets/28535394/f0301488-4002-4942-82c9-db995f827bad)

**Comment by AntoineRelief** [comment]
@estelafs 
if possible, it should not be called the first time we enter

**Comment by AntoineRelief** [comment]
should be fixed in this commit:
https://github.com/ReliefApplications/ems-frontend/commit/9fc950494d75106e4ad9e372ae29cfaa2458d3d8

**Pull request closed without merging**
