### PR TITLE
feat/AB#105461_UI-keep-vertical-tabs-fixed-when-scrolling-down

### PR DESCRIPTION
**Pull request by unai-reliefapp**
# Description

feat: apply y axis scroll for ui tabs content by checking the inherited height on vertical tabs 
feat: adapt needed styles of parent component for the previously mentioned reason

⚠️ **Considerations**⚠️ 

- It could happen that once merged in beta-unstable, the new ui tabs in vertical set there are not working with the new scroll of ui tabs content, because the parent component height or display type is not set=>should be double checked for those cases
- The tabs widget settings modal now can have a double scroll, as there is the scroll of the vertical tabs for settings, and the scroll within the content, which is totally fine given the requested behavior for ui tabs in vertical

I could not find an easy way to manage this scroll behaviors for ui-tabs vertical without a deep check with dialogs, or a big refactor. If want to work with fixed elements, then it would take much time and check and code changes, which may affect rest of the application.

## Useful links

- [Link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/105461)

## Type of change

Please delete options that are not relevant.

- [X] Improvement (refactor or addition to existing functionality)

# How Has This Been Tested?

Just change the `max-h-full` class in the tabs.component for `max-h-[50%]` to test how the scroll behaves for those ui tabs in vertical, or without affecting how the ui tabs are displayed

## Screenshots

Please include screenshots of this change. If this issue is only back-end related, and does not involve any visual change of the platform, you can skip this part.

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# More explanation
https://www.loom.com/share/05a716d61b9744faaf51fb304c21d1e5?sid=f87cf896-582a-4f76-93ae-8ceed801b145

### CODE REVIEW

**Comment by AntoineRelief** [comment]
@unai-reliefapp 
seems to do the trick for vertical tabs but it doesn't work for horizontal ones in some cases

For example, if you take the edition of roles in applications, it's adding another scrollbar to the content:

Capture d’écran 2024-11-08 à 13 00 58

and it's making it quite hard to use

I'll put it as draft
it's not a big priority, so when you go back on the project, we should first clear the rest of the todo before going back on this one

**Comment by unai-reliefapp** [comment]
@AntoineRelief Update fix for those cases in the horizontal scrollbar
I have a medical appointment now(hopefully last one in a veeeeery long time) and as it was a quick fix I decided to finish this one up before leaving.

KR, Unai

**Comment by unai-reliefapp** [comment]
@AntoineRelief  Closing it as the renaming of button action of components and rebase is doing very difficult the merge, Ill create a new PR with the changes

PD: Holy cr*p, I closed this one thinking it was the one for the form action buttons, this PR is fine @AntoineRelief

**Comment by AntoineRelief** [comment]
@unai-reliefapp 

I merged the sticky approach, that requires less changes

thus, there's still the same issue I've described for like 3 modals, but that's already an improvement

**Pull request closed without merging**
