### PR TITLE
AB#96226 + AB#96638 Email Notifications Fixes

### PR DESCRIPTION
**Pull request by HasnatL-Adapptlimited**
# Description

- Step 1 only had loader on direct send
- Step 5 and Step 6 only load once data is ready
- Too many records alert, still displays when apply filter clicked even if user closes ui-alert

## Tickets

- [ ] https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/96226/
- [ ] https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/96683/

## Other Issues Fixed

- [ ] Too many records alert not displaying again, if user closes alert -- Fixed 
- [ ] Added Tooltip and more informative tooltip text for field select dropdown

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by HasnatL-Adapptlimited** [comment]
Hey @AntoineRelief,

First PR Has been opened

cc: @Vaishali1709 @morgang-adappt

**Comment by AntoineRelief** [comment]
Thanks @HasnatL-Adapptlimited!

I'll start to look at the code and push it on UAT after the review

cc: @Vaishali1709 @morgang-adappt

**Comment by AntoineRelief** [comment]
@HasnatL-Adapptlimited 

Just merged it
I'll now proceed with the deployment

cc: @Vaishali1709 @morgang-adappt

**Comment by Vaishali1709** [comment]
@AntoineRelief  Please do let us know once its deployed in UAT

**Comment by AntoineRelief** [comment]
@Vaishali1709 

It's now deployed on UAT

**Pull request merged**
