### PR TITLE
Feat/ab#84920 give correct default texts to created at and modified at filters

### PR DESCRIPTION
**Pull request by RenzoPrats**
# Description

Feat:  Give correct default texts to createdAt and modifiedAt filters.

## Useful links

[ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/84920)

## Type of change

- [X] Improvement (refactor or addition to existing functionality)

# How Has This Been Tested?

It has been tested checking if the filter text for createdAt and modifiedAt are correctly.

## Screenshots

Captura de tela de 2024-02-01 14-44-29
Captura de tela de 2024-02-01 14-44-17

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# More explanation
https://www.loom.com/share/05a716d61b9744faaf51fb304c21d1e5?sid=f87cf896-582a-4f76-93ae-8ceed801b145

### CODE REVIEW

**Comment by AntoineRelief** [comment]
@RenzoPrats 
i don't agree with these changes
you are editing texts that can be shared by multiple filter elements, not only date ones
we should prefer to do some refactoring

**Comment by NathanHGit** [comment]
@RenzoPrats @AntoineRelief 
It works fine.

I noticed that we have the same issue when creating an aggregation, but it could be out of the scope of the ticket
image

**Comment by AntoineRelief** [comment]
@NathanHGit 
well found
I think that's fine for this one

**Review by NathanHGit — APPROVED** [review]

**Comment by AntoineRelief** [comment]
@RenzoPrats 
all good 👍

**Pull request merged**
