### PR TITLE
AB#76508_fix_grids_loading_multiple_times

### PR DESCRIPTION
**Pull request by MwanPygmay**
# Description

Fix the charts loading multiple times. Not 100% satisfied with my fix, as it involves a big throttle time that freezes context filters changing. If someone has a better fix for this, please share.

## Useful links

[Please insert link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/76508/)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Added chart, tried to reload page and activating/deactivating dashboard filter

## Screenshots

# Checklist:

( * == Mandatory ) 

- [x] * I have set myself as assignee of the pull request
- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [x] * I have commented my code, particularly in hard-to-understand areas
- [x] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by unai-reliefapp** [comment]
Ey @MwanPygmay , I pushed a new approach.

What I did is merge the isFilterEnabled and filter value into the same stream(as it's used in all widget same way to trigger filter changes) and only trigger them whenever a filter value changes, on enabling filter we are adding the dashboard filter component which would emit a default value on init and on destroy, therefor would be always correctly triggered but we only would take care of filter values that are different.

I also fix some timeout listeners to avoid memory leaks 👍

**Comment by AntoineRelief** [comment]
@unai-reliefapp 
I don't see the same logic applied to the grid widget, any reason why?

**Comment by AntoineRelief** [comment]
@unai-reliefapp 
if you access a page with a dashboard filter, the value of the isFilterEnabled seems to be false, and so, the context filter cannot be passed to the widgets that would use it

putting back the ticket into todo

**Review by AntoineRelief — CHANGES_REQUESTED** [review]
not working as it is

the dashboard filter isn't passed to the widgets if you open a page that uses it

**Comment by AntoineRelief** [comment]
video:
https://www.loom.com/share/1c3c387dcddf4210aa4b7ebca7546d81?sid=b89a9ee7-e298-474d-8cb9-9eb5b1cae455

**Comment by unai-reliefapp** [comment]
> @unai-reliefapp I don't see the same logic applied to the grid widget, any reason why?

the only grid using that logic was the aggregation-grid and keep it there only.
Core-grid component is subscribing but just to the filter$ value, even though that filter value is not used in the reloadData method: https://github.com/ReliefApplications/oort-frontend/blob/AB%2376508_fix_grids_loading_multiple_times/libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts#L318

**Comment by unai-reliefapp** [comment]
@AntoineRelief Last commit makes the related widget to only listen to the filter values, as the isFilterEnable property it's only used in the dashboard filter injection method.
So we still keep sending the isFilterEnable value on toggle and application load, but the widget only listen to the filter value changes and the dashboard filter injection method will handle the apply or not of filters if enable or not.
On enable/disable dashboard filter this will still work as on init and on destroy we are triggering a filter value(on destroy an empty object, no filter), so with this the whole flow is closed and reliable
Thanks fo the spot
KR, Unai

**Pull request merged**
