### PR TITLE
Fix/ab#82564 widgets unnecessarily reloading

### PR DESCRIPTION
**Pull request by NathanHGit**
# Description

Widgets are unnecessarily reloaded when dashboard filters are used. Adding a regex expression to prevent unwanted reloading. 

For the maps, I added the contextFilters variable to the layer to be able to read them from the map component. I didn't find a better way of doing it. 

I was looking at `featureSatisfiesFilter()` into `layer.ts` during my investigation and it may be unused. It is called if `this.filter` isn't empty or when it is initialized: `this.filter = get(options, 'filter', DEFAULT_LAYER_FILTER);` it seems that `options.filter` doesn't exist, then `DEFAULT_LAYER_FILTER` is used. I don't know all the features of the project that's why I didn't remove this part.

## Useful links

- [Please insert link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/82564/)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Setup: I created a dashboard and added each widget in it. I created a context filter.
Test: I tried to modify the dashboard filter to see if widgets were reloaded or not. I did the same test with filter configuration for each of them.

## Screenshots

peek
In this example, the pie chart widget is the only one configured with context filters.

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# More explanation
https://www.loom.com/share/05a716d61b9744faaf51fb304c21d1e5?sid=f87cf896-582a-4f76-93ae-8ceed801b145

### CODE REVIEW

**Comment by unai-reliefapp** [comment]
Hi @NathanHGit , just wondering, if a widget contains some contextFilters in their settings, and we then delete them from the settings would it be triggered because it's already subscribed previously or the widget state is reset?

And maybe same on the other way around, if no contextFilters set and then setting them

Also contextFilters can contain fix values, without the need of {{filter.}} notation
image

Would it take them in account?

KR, Unai

**Comment by NathanHGit** [comment]
@unai-reliefapp for you first question, it works because the widget is reloaded after saving the settings. Here is a demonstration: 

peek

Concerning the second one, it works as well:

image

Both show the same data but I added this filter on the left map:

image

According to my knowledge, this kind of filter applies once when loading and then never change.

**Comment by unai-reliefapp** [comment]
> Concerning the second one, it works as well:
> 
> image
> 
> Both show the same data but I added this filter on the left map:
> 
> image
> 
> According to my knowledge, this kind of filter applies once when loading and then never change.

I was concerned because of the regex: https://github.com/ReliefApplications/ems-frontend/blob/a520dfd6f126b16020c6c496668d84133aebeb2b/libs/shared/src/lib/services/context/context.service.ts#L48

As those fix values may not contain the {{filter.}} notation and the regex would be falsy not triggering the subscription even if the widget has contextFilters.

If it works fine 👍

**Comment by AntoineRelief** [comment]
@NathanHGit 
cc @unai-reliefapp 
looks good to me, will now try live with WHO applications 👍

**Pull request merged**
