### PR TITLE
Feat/ab#74109 grids apply automatic columns width calculation on grid

### PR DESCRIPTION
**Pull request by unai-reliefapp**
# Description

Following the requirements, here is the content with all the calculations:
image

For a grid with 9 active columns and a grid with the total width of 1016px:
Average column width = 1016/9 = 112.89
Max average column width = 112.89 * 2 = 225.78
Min average column width = 112.89 / 2 = 56.4

Taking in account that the body document contains a font-size of 16px and that most of the fonts have a 3:5 aspect ration, we calculate each character width: which give us:
Character width in pixels = 16 * 0.6 = 9.6

Therefor, max number of characters would be = 225.78 / 9.6 = 23 => to floor
min number of characters would be = 56.4 / 9.6 = 5 => to floor
image

We got longest content(in character length) of each column in the view
image

Taking in account the max and min character, final result would be:
image

And those values would be set as percentages to the whole sum of those values plus update them to match min and max values, with a final result of
image

Then this percentage values would be taken for the grid width and set for their related columns

## Useful links

- [Link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/74109)

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [ ] Test A
- [ ] Test B

## Screenshots

Please include screenshots of this change. If this issue is only back-end related, and does not involve any visual change of the platform, you can skip this part.

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings

### CODE REVIEW

**Review by RenzoPrats — COMMENTED** [review]
Hey @unai-reliefapp, I saw the changes and you really did some good improvements in the previous PR that I've done and it's working fine! I just have one question: in this example 
Captura de tela de 2023-09-19 17-06-21
Captura de tela de 2023-09-19 17-06-06
we can see that the fields takes up all the space and we have to scroll to see icon for details, this is what we want? I remember that when I worked on this I decrease the total available space to try to cover this question. So dispite of that, if this is the way we want so everything looks good to me!

**Comment by unai-reliefapp** [comment]
> Hey @unai-reliefapp, I saw the changes and you really did some good improvements in the previous PR that I've done and it's working fine! I just have one question: in this example Captura de tela de 2023-09-19 17-06-21 Captura de tela de 2023-09-19 17-06-06 we can see that the fields takes up all the space and we have to scroll to see icon for details, this is what we want? I remember that when I worked on this I decrease the total available space to try to cover this question. So dispite of that, if this is the way we want so everything looks good to me!

ey @RenzoPrats , thanks for checking the PR.
What they wanted is to set the max width available taking in account the total number of characters plus also some other condition, so it's expected. Anyway, can you send me back that application ID so i can do a further check?
Thanks

**Comment by unai-reliefapp** [comment]
Double checked and clarified with @RenzoPrats , true that Details column is beyond the rest of the columns for each data list used but the behavior is similar to those, as it's not a fixed column as the checkbox select or the three dots column.

Good to go 👍

**Comment by AntoineRelief** [comment]
@RenzoPrats @unai-reliefapp 
closing this one due to merge conflicts, but I duplicated the exact code there:
https://github.com/ReliefApplications/ems-frontend/commit/915d8954be30518b907c621bd200539dcb85fade

thanks!

**Pull request closed without merging**
